### ISSUE TITLE
Support for bm60ec

### ISSUE THREAD

**Issue by Lozilla** [the-via/firmware#13]
Hi, the bm60ec firmware provided by krepublic doesnt seems to be recognised by VIA, any ideas?

**Comment by wilba** [comment]
I do not see the name BM60EC in the VIA definitions, so no one has added support for it yet.

**Comment by Silenc3IsGold3n** [comment]
https://drive.google.com/drive/folders/1j6iLnYhzO597L2F07vygnBp8qpIIQ0qt

It looks like it is supported  there is a there is a working hex file and layout
