### ISSUE TITLE
Volume media control is not affecting sound

### ISSUE THREAD

**Issue by JulianNorton** [the-via/firmware#25]
I am using a Discipline keyboard and have tested the switches:

![Screen Shot 2021-08-02 at 10 36 13 AM](https://user-images.githubusercontent.com/2412992/127878708-c7732ae8-3145-4fea-8066-34d1c3aa03cd.png)
![Screen Shot 2021-08-02 at 10 35 52 AM](https://user-images.githubusercontent.com/2412992/127878740-9407eb86-920d-45b7-8c9f-161489e10d7b.png)
![Screen Shot 2021-08-02 at 10 37 05 AM](https://user-images.githubusercontent.com/2412992/127878748-4b601206-6deb-4e79-bf9c-2a97856a144a.png)
Is this anything someone has experienced before, or anything someone recommends I can do to continue to troubleshoot? I have tested this on both mac and pc, and the sound media keys are not functioning.

Thank you!

**Comment by wilba** [comment]
QMK firmware for this MCU didn't support the extra keys interface which has the media keys, I believe this was fixed, try using latest firmware.

**Comment by JulianNorton** [comment]
Thanks, I'll go try on their documentation. Trouble I ran into was that it tells me to hit "function R" to enter bootloader mode, but I'm not sure which is the function key in the mapping. I didn't see that as an option.

**Comment by wilba** [comment]
You should be able to enter bootloader by holding the Esc key while plugging in the USB.
