### ISSUE TITLE
Iron165 VIA Firmware Incorrect

### ISSUE THREAD

**Issue by MudkipMao** [the-via/firmware#4]
Hi Wilba/Olivia,

I hope this is the right place to report this issue.

The VIA firmware .bin file for the Iron165 is currently incorrect on the website. It is not compiled with the VIA_ENABLE=yes makefile flag so we have seen a lot of people running into an issue when flashing their PCB's.

I have committed a fix for this and all that needs to be done is to re-compile the firmware from top of tree and re-upload it.

QMK PR: https://github.com/qmk/qmk_firmware/pull/9298

Thanks for the hard work!

**Comment by Wilba6582** [comment]
Firmware has been built from master and hosted.
