### ISSUE TITLE
Rama Works U80 - issues with the new framework

### ISSUE THREAD

**Issue by farbodsalimi** [the-via/firmware#5]
My keyboard stops working after my laptop goes to sleep. I saw [this new commit](https://github.com/the-via/firmware/commit/7b18a01e89b0ae3c8979bc4f6dbfd016654d5bff) and thought it was a software issue so I flashed my keyboard but after flashing I have all sorts of other issues:

- I cannot change the settings through Via anymore (Via and my keyboard get frozen when I change the settings)
- If I don't turn the lighting off with the short keys, my keyboard starts randomly triggering switches.

Could you please let me know if it's a software issue or a hardware/PCB issue?

**Comment by Wilba6582** [comment]
Did you download the firmware directly from github?

If yes, the firmware is probably corrupted.

Download it from https://caniusevia.com/docs/download_firmware

**Comment by farbodsalimi** [comment]
@Wilba6582 No I downloaded it from https://caniusevia.com/docs/download_firmware

**Comment by Wilba6582** [comment]
This might be a firmware install problem. Can you download it again and install it again? The downloaded firmware works fine on my PCB.

**Comment by farbodsalimi** [comment]
@Wilba6582 Actually I've flashed it 3-4 times and nothing changed.

I don't know if this helps or not but this is what I've done:

QMK Toolbox 0.0.18
VIA 1.3.1

1) Hold Esc and plugin (I initially did Esc + Space)
2) Open the hex file
3) Flash
4) Unplug
(I think the last time I also did reset EEPROM.)

Is there any other way to completely reset the memory?

**Comment by Wilba6582** [comment]
I can't explain why it isn't working, I've tested this exact firmware on the PCB and it's fine.

Contact Rama Works support: https://rama.works/contact about getting a replacement PCB.

**Comment by farbodsalimi** [comment]
@Wilba6582 I see sure. Thank you for your help and your prompt replies!

**Comment by farbodsalimi** [comment]
@kikin81 sorry I totally missed this comment. So that PCB was faulty and I got a replacement. However, the replacement is also not perfect it randomly fails to wake up.
